#include "font.h"

TTF_Font *loadFont( char *filename, int size )
{
  TTF_Font *font = TTF_OpenFont( filename, size );

  if( font == NULL )
  {
    printf( "Failed to open font %s: %s\n", filename, TTF_GetError() );
    exit(1);
  }

  return font;
}

void closeFont( TTF_Font* font )
{
  if( font != NULL )
  {
    TTF_CloseFont( font );
  }
}

void drawString( char *text, int x, int y, TTF_Font *font )
{
  SDL_Rect dest;
  SDL_Surface *textSurface;
  SDL_Texture *textTexture;
  SDL_Color foregroundColor, backgroundColor;

  /* white text on black background */
  foregroundColor.r = 255;
  foregroundColor.g = 255;
  foregroundColor.b = 255;

  backgroundColor.r = 0;
  backgroundColor.g = 0;
  backgroundColor.b = 0;

  /* fill an SDL_Surface with a string image generated by SDL_TTF */
  textSurface = TTF_RenderUTF8_Shaded( font, text, foregroundColor, backgroundColor );

  /* convert from surface to texture */
  textTexture = SDL_CreateTextureFromSurface( game.gameRenderer, textSurface );

  dest.x = x;
  dest.y = y;

  SDL_QueryTexture( textTexture, NULL, NULL, &dest.w, &dest.h );
  SDL_RenderCopy( game.gameRenderer, textTexture, NULL, &dest );
  SDL_FreeSurface( textSurface );
  SDL_DestroyTexture( textTexture );
}
