#include "font.h"

TTF_Font *loadFont( char *filename, int size )
{
  TTF_Font *font = TTF_OpenFont( filename, size );

  if( font == NULL )
  {
    printf( "Failed to open font %s: %s\n", filename, TTF_GetError() );
    exit(1);
  }

  return font;
}

void closeFont( TTF_Font* font )
{
  if( font != NULL )
  {
    TTF_CloseFont( font );
  }
}

void drawString( char *text, int x, int y, TTF_Font *font, int centerX, int centerY )
{
  SDL_Rect dest;
  SDL_Surface *textSurface;
  SDL_Texture *textTexture;
  SDL_Color foregroundColor, backgroundColor;

  /* white text on black background */
  foregroundColor.r = 255;
  foregroundColor.g = 255;
  foregroundColor.b = 255;

  backgroundColor.r = 0;
  backgroundColor.g = 0;
  backgroundColor.b = 0;

  /* fill an SDL_Surface with a string image generated by SDL_TTF*/
  textSurface = TTF_RenderUTF8_Shaded( font, text, foregroundColor, backgroundColor );

  dest.x = ( centerX == 1 ? ( SCREEN_WIDTH - textSurface->w ) /2 : x );
  dest.y = ( centerY == 1 ? ( SCREEN_HEIGHT - textSurface->h ) / 2 : y );
  dest.w = textSurface->w;
  dest.h = textSurface->h;

  /* convert from surface to texture*/
  textTexture = SDL_CreateTextureFromSurface( game.gameRenderer, textSurface );

  SDL_RenderCopy( game.gameRenderer, textTexture, NULL, &dest );
  SDL_FreeSurface( textSurface );
  SDL_DestroyTexture( textTexture );
}
